package com.mmss.model;

public class Usertable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usertable.id
     *
     * @ibatorgenerated Thu Jun 08 18:57:31 IST 2017
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column usertable.name
     *
     * @ibatorgenerated Thu Jun 08 18:57:31 IST 2017
     */
    private String name;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usertable.id
     *
     * @return the value of usertable.id
     *
     * @ibatorgenerated Thu Jun 08 18:57:31 IST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usertable.id
     *
     * @param id the value for usertable.id
     *
     * @ibatorgenerated Thu Jun 08 18:57:31 IST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column usertable.name
     *
     * @return the value of usertable.name
     *
     * @ibatorgenerated Thu Jun 08 18:57:31 IST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column usertable.name
     *
     * @param name the value for usertable.name
     *
     * @ibatorgenerated Thu Jun 08 18:57:31 IST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}